# Generated by Django 6.0.4 on 2026-04-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='upload_at',
            new_name='uploaded_at',
        ),
    ]
