# Generated by Django 6.0.4 on 2026-05-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestionsession',
            name='answer',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
