# Generated by Django 6.0.4 on 2026-05-07 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('job_applications', '0002_rename_jobappliaction_jobapplication_and_more'),
        ('resumes', '0002_rename_upload_at_resume_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiquestionsession',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='aiquestionsession',
            name='question',
        ),
        migrations.AlterField(
            model_name='aiquestionsession',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='job_applications.jobapplication'),
        ),
        migrations.AlterField(
            model_name='aiquestionsession',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='aiquestionsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_engine.aiquestionsession')),
            ],
        ),
    ]
