# Generated by Django 6.0.4 on 2026-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aiquestionsession_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestionsession',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
