# Generated by Django 6.0.4 on 2026-06-05 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_aiquestionsession_answer'),
        ('job_applications', '0002_alter_generatedresume_base_resume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.TextField()),
                ('current_category', models.CharField(max_length=100)),
                ('total_score', models.FloatField(default=0)),
                ('questions_answered', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_applications.generatedresume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MockInterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('score', models.FloatField()),
                ('technical_score', models.FloatField()),
                ('communication_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('feedback', models.TextField()),
                ('ideal_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.mockinterviewsession')),
            ],
        ),
    ]
