# ==========================================
# HTTP → HTTPS
# ==========================================

server {
    listen 80;
    server_name careerforge.vexlite.dev;

    client_max_body_size 50M;

    # Keep this available for Let's Encrypt renewal
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Everything else goes to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}


# ==========================================
# HTTPS
# ==========================================

server {
    listen 443 ssl;
    server_name careerforge.vexlite.dev;

    client_max_body_size 50M;

    # Let's Encrypt certificate
    ssl_certificate /etc/letsencrypt/live/careerforge.vexlite.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/careerforge.vexlite.dev/privkey.pem;

    # React frontend
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Accounts
    location /accounts/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django AI Engine
    location /ai_engine/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Resumes
    location /resumes/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Job Applications
    location /job_applications/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django Admin
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Media
    location /media/ {
	alias /media/;
        
    }

    # Static files
    location /static/ {
        alias /static/;
    }
}
