# Generated by Django 6.0.4 on 2026-05-17 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedresume',
            name='base_resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_versions', to='resumes.resume'),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='file',
            field=models.FileField(upload_to='generated_resumes/'),
        ),
        migrations.AlterField(
            model_name='generatedresume',
            name='job_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resumes', to='job_applications.jobapplication'),
        ),
    ]
