# Generated by Django 6.0.4 on 2026-05-04 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobAppliaction',
            new_name='JobApplication',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='Company',
            new_name='company',
        ),
    ]
